[[constraint]]
  name = "github.com/Azure/azure-amqp-common-go"
  version = "0.3.2"

[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.6.2"
